/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as MinhaBaseRouteImport } from './routes/minha-base'
import { Route as MeusProjetosRouteImport } from './routes/meus-projetos'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as DocMestreRouteImport } from './routes/doc-mestre'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetodoIndexRouteImport } from './routes/metodo.index'
import { Route as MetodoPilar4RouteImport } from './routes/metodo.pilar-4'
import { Route as MetodoPilar3RouteImport } from './routes/metodo.pilar-3'
import { Route as MetodoPilar2RouteImport } from './routes/metodo.pilar-2'
import { Route as MetodoPilar1RouteImport } from './routes/metodo.pilar-1'
import { Route as MetodoConsultoriaIaRouteImport } from './routes/metodo.consultoria-ia'
import { Route as ApiHotmartWebhookRouteImport } from './routes/api/hotmart-webhook'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as MetodoPilar4IndexRouteImport } from './routes/metodo.pilar-4.index'
import { Route as MetodoPilar3IndexRouteImport } from './routes/metodo.pilar-3.index'
import { Route as MetodoPilar2IndexRouteImport } from './routes/metodo.pilar-2.index'
import { Route as MetodoPilar1IndexRouteImport } from './routes/metodo.pilar-1.index'
import { Route as MetodoConsultoriaIaIndexRouteImport } from './routes/metodo.consultoria-ia.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as MetodoPilar4TrafegoPagoRouteImport } from './routes/metodo.pilar-4.trafego-pago'
import { Route as MetodoPilar4PassoAPassoRouteImport } from './routes/metodo.pilar-4.passo-a-passo'
import { Route as MetodoPilar4LowTicketRouteImport } from './routes/metodo.pilar-4.low-ticket'
import { Route as MetodoPilar4LancamentosRouteImport } from './routes/metodo.pilar-4.lancamentos'
import { Route as MetodoPilar4FundacaoRouteImport } from './routes/metodo.pilar-4.fundacao'
import { Route as MetodoPilar4EventosPresenciaisRouteImport } from './routes/metodo.pilar-4.eventos-presenciais'
import { Route as MetodoPilar4CopyRouteImport } from './routes/metodo.pilar-4.copy'
import { Route as MetodoPilar4ConclusaoRouteImport } from './routes/metodo.pilar-4.conclusao'
import { Route as MetodoPilar4AtalhoSkillRouteImport } from './routes/metodo.pilar-4.atalho-skill'
import { Route as MetodoPilar4AltoTicketRouteImport } from './routes/metodo.pilar-4.alto-ticket'
import { Route as MetodoPilar3ValidarProdutoRouteImport } from './routes/metodo.pilar-3.validar-produto'
import { Route as MetodoPilar3DescobrirRouteImport } from './routes/metodo.pilar-3.descobrir'
import { Route as MetodoPilar3ConclusaoRouteImport } from './routes/metodo.pilar-3.conclusao'
import { Route as MetodoPilar2TomDeVozRouteImport } from './routes/metodo.pilar-2.tom-de-voz'
import { Route as MetodoPilar2RedesSociaisRouteImport } from './routes/metodo.pilar-2.redes-sociais'
import { Route as MetodoPilar2PesquisaMercadoRouteImport } from './routes/metodo.pilar-2.pesquisa-mercado'
import { Route as MetodoPilar2PaginaProfissionalRouteImport } from './routes/metodo.pilar-2.pagina-profissional'
import { Route as MetodoPilar2MetodoRouteImport } from './routes/metodo.pilar-2.metodo'
import { Route as MetodoPilar2IdentidadeVisualRouteImport } from './routes/metodo.pilar-2.identidade-visual'
import { Route as MetodoPilar2IdentidadeRouteImport } from './routes/metodo.pilar-2.identidade'
import { Route as MetodoPilar2ConsultoriaImagemRouteImport } from './routes/metodo.pilar-2.consultoria-imagem'
import { Route as MetodoPilar2ConclusaoRouteImport } from './routes/metodo.pilar-2.conclusao'
import { Route as MetodoPilar1DetetiveDoTempoRouteImport } from './routes/metodo.pilar-1.detetive-do-tempo'
import { Route as MetodoPilar1ConclusaoRouteImport } from './routes/metodo.pilar-1.conclusao'
import { Route as MetodoPilar1AprendaIaRouteImport } from './routes/metodo.pilar-1.aprenda-ia'
import { Route as MetodoConsultoriaIaComoUsarRouteImport } from './routes/metodo.consultoria-ia.como-usar'
import { Route as AuthenticatedAdminRankingRouteImport } from './routes/_authenticated/admin/ranking'
import { Route as AuthenticatedAdminMentoradasRouteImport } from './routes/_authenticated/admin/mentoradas'
import { Route as AuthenticatedAdminConteudoRouteImport } from './routes/_authenticated/admin/conteudo'
import { Route as MetodoPilar3PaginaVendasIndexRouteImport } from './routes/metodo.pilar-3.pagina-vendas.index'
import { Route as MetodoPilar3CriarProdutoIndexRouteImport } from './routes/metodo.pilar-3.criar-produto.index'
import { Route as MetodoPilar3ComoEntregarIndexRouteImport } from './routes/metodo.pilar-3.como-entregar.index'
import { Route as MetodoPilar2RedesSociaisIndexRouteImport } from './routes/metodo.pilar-2.redes-sociais.index'
import { Route as MetodoPilar1DetetiveDoTempoIndexRouteImport } from './routes/metodo.pilar-1.detetive-do-tempo.index'
import { Route as MetodoPilar1AprendaIaIndexRouteImport } from './routes/metodo.pilar-1.aprenda-ia.index'
import { Route as MetodoPilar3PaginaVendasAulaRouteImport } from './routes/metodo.pilar-3.pagina-vendas.$aula'
import { Route as MetodoPilar3FerramentasSlugRouteImport } from './routes/metodo.pilar-3.ferramentas.$slug'
import { Route as MetodoPilar3CriarProdutoAulaRouteImport } from './routes/metodo.pilar-3.criar-produto.$aula'
import { Route as MetodoPilar3ComoEntregarFormatoRouteImport } from './routes/metodo.pilar-3.como-entregar.$formato'
import { Route as MetodoPilar2RedesSociaisInstagramRouteImport } from './routes/metodo.pilar-2.redes-sociais.instagram'
import { Route as MetodoPilar1DetetiveDoTempoRelatorioRouteImport } from './routes/metodo.pilar-1.detetive-do-tempo.relatorio'
import { Route as MetodoPilar1DetetiveDoTempoPlanoRouteImport } from './routes/metodo.pilar-1.detetive-do-tempo.plano'
import { Route as MetodoPilar1AprendaIaVideosRouteImport } from './routes/metodo.pilar-1.aprenda-ia.videos'
import { Route as MetodoPilar1AprendaIaProdutividadeRouteImport } from './routes/metodo.pilar-1.aprenda-ia.produtividade'
import { Route as MetodoPilar1AprendaIaPrincipaisIasRouteImport } from './routes/metodo.pilar-1.aprenda-ia.principais-ias'
import { Route as MetodoPilar1AprendaIaToolRouteImport } from './routes/metodo.pilar-1.aprenda-ia.$tool'
import { Route as AuthenticatedAdminMentoradasIdRouteImport } from './routes/_authenticated/admin/mentoradas.$id'
import { Route as MetodoPilar2RedesSociaisInstagramIndexRouteImport } from './routes/metodo.pilar-2.redes-sociais.instagram.index'
import { Route as MetodoPilar1AprendaIaToolIndexRouteImport } from './routes/metodo.pilar-1.aprenda-ia.$tool.index'
import { Route as MetodoPilar2RedesSociaisInstagramFormatoRouteImport } from './routes/metodo.pilar-2.redes-sociais.instagram.$formato'
import { Route as MetodoPilar1AprendaIaClaudeInstalarSkillsRouteImport } from './routes/metodo.pilar-1.aprenda-ia.claude.instalar-skills'
import { Route as MetodoPilar1AprendaIaToolLessonSlugRouteImport } from './routes/metodo.pilar-1.aprenda-ia.$tool.$lessonSlug'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaBaseRoute = MinhaBaseRouteImport.update({
  id: '/minha-base',
  path: '/minha-base',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusProjetosRoute = MeusProjetosRouteImport.update({
  id: '/meus-projetos',
  path: '/meus-projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const DocMestreRoute = DocMestreRouteImport.update({
  id: '/doc-mestre',
  path: '/doc-mestre',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoIndexRoute = MetodoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetodoRoute,
} as any)
const MetodoPilar4Route = MetodoPilar4RouteImport.update({
  id: '/pilar-4',
  path: '/pilar-4',
  getParentRoute: () => MetodoRoute,
} as any)
const MetodoPilar3Route = MetodoPilar3RouteImport.update({
  id: '/pilar-3',
  path: '/pilar-3',
  getParentRoute: () => MetodoRoute,
} as any)
const MetodoPilar2Route = MetodoPilar2RouteImport.update({
  id: '/pilar-2',
  path: '/pilar-2',
  getParentRoute: () => MetodoRoute,
} as any)
const MetodoPilar1Route = MetodoPilar1RouteImport.update({
  id: '/pilar-1',
  path: '/pilar-1',
  getParentRoute: () => MetodoRoute,
} as any)
const MetodoConsultoriaIaRoute = MetodoConsultoriaIaRouteImport.update({
  id: '/consultoria-ia',
  path: '/consultoria-ia',
  getParentRoute: () => MetodoRoute,
} as any)
const ApiHotmartWebhookRoute = ApiHotmartWebhookRouteImport.update({
  id: '/api/hotmart-webhook',
  path: '/api/hotmart-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MetodoPilar4IndexRoute = MetodoPilar4IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetodoPilar4Route,
} as any)
const MetodoPilar3IndexRoute = MetodoPilar3IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetodoPilar3Route,
} as any)
const MetodoPilar2IndexRoute = MetodoPilar2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetodoPilar2Route,
} as any)
const MetodoPilar1IndexRoute = MetodoPilar1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetodoPilar1Route,
} as any)
const MetodoConsultoriaIaIndexRoute =
  MetodoConsultoriaIaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MetodoConsultoriaIaRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const MetodoPilar4TrafegoPagoRoute = MetodoPilar4TrafegoPagoRouteImport.update({
  id: '/trafego-pago',
  path: '/trafego-pago',
  getParentRoute: () => MetodoPilar4Route,
} as any)
const MetodoPilar4PassoAPassoRoute = MetodoPilar4PassoAPassoRouteImport.update({
  id: '/passo-a-passo',
  path: '/passo-a-passo',
  getParentRoute: () => MetodoPilar4Route,
} as any)
const MetodoPilar4LowTicketRoute = MetodoPilar4LowTicketRouteImport.update({
  id: '/low-ticket',
  path: '/low-ticket',
  getParentRoute: () => MetodoPilar4Route,
} as any)
const MetodoPilar4LancamentosRoute = MetodoPilar4LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => MetodoPilar4Route,
} as any)
const MetodoPilar4FundacaoRoute = MetodoPilar4FundacaoRouteImport.update({
  id: '/fundacao',
  path: '/fundacao',
  getParentRoute: () => MetodoPilar4Route,
} as any)
const MetodoPilar4EventosPresenciaisRoute =
  MetodoPilar4EventosPresenciaisRouteImport.update({
    id: '/eventos-presenciais',
    path: '/eventos-presenciais',
    getParentRoute: () => MetodoPilar4Route,
  } as any)
const MetodoPilar4CopyRoute = MetodoPilar4CopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => MetodoPilar4Route,
} as any)
const MetodoPilar4ConclusaoRoute = MetodoPilar4ConclusaoRouteImport.update({
  id: '/conclusao',
  path: '/conclusao',
  getParentRoute: () => MetodoPilar4Route,
} as any)
const MetodoPilar4AtalhoSkillRoute = MetodoPilar4AtalhoSkillRouteImport.update({
  id: '/atalho-skill',
  path: '/atalho-skill',
  getParentRoute: () => MetodoPilar4Route,
} as any)
const MetodoPilar4AltoTicketRoute = MetodoPilar4AltoTicketRouteImport.update({
  id: '/alto-ticket',
  path: '/alto-ticket',
  getParentRoute: () => MetodoPilar4Route,
} as any)
const MetodoPilar3ValidarProdutoRoute =
  MetodoPilar3ValidarProdutoRouteImport.update({
    id: '/validar-produto',
    path: '/validar-produto',
    getParentRoute: () => MetodoPilar3Route,
  } as any)
const MetodoPilar3DescobrirRoute = MetodoPilar3DescobrirRouteImport.update({
  id: '/descobrir',
  path: '/descobrir',
  getParentRoute: () => MetodoPilar3Route,
} as any)
const MetodoPilar3ConclusaoRoute = MetodoPilar3ConclusaoRouteImport.update({
  id: '/conclusao',
  path: '/conclusao',
  getParentRoute: () => MetodoPilar3Route,
} as any)
const MetodoPilar2TomDeVozRoute = MetodoPilar2TomDeVozRouteImport.update({
  id: '/tom-de-voz',
  path: '/tom-de-voz',
  getParentRoute: () => MetodoPilar2Route,
} as any)
const MetodoPilar2RedesSociaisRoute =
  MetodoPilar2RedesSociaisRouteImport.update({
    id: '/redes-sociais',
    path: '/redes-sociais',
    getParentRoute: () => MetodoPilar2Route,
  } as any)
const MetodoPilar2PesquisaMercadoRoute =
  MetodoPilar2PesquisaMercadoRouteImport.update({
    id: '/pesquisa-mercado',
    path: '/pesquisa-mercado',
    getParentRoute: () => MetodoPilar2Route,
  } as any)
const MetodoPilar2PaginaProfissionalRoute =
  MetodoPilar2PaginaProfissionalRouteImport.update({
    id: '/pagina-profissional',
    path: '/pagina-profissional',
    getParentRoute: () => MetodoPilar2Route,
  } as any)
const MetodoPilar2MetodoRoute = MetodoPilar2MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => MetodoPilar2Route,
} as any)
const MetodoPilar2IdentidadeVisualRoute =
  MetodoPilar2IdentidadeVisualRouteImport.update({
    id: '/identidade-visual',
    path: '/identidade-visual',
    getParentRoute: () => MetodoPilar2Route,
  } as any)
const MetodoPilar2IdentidadeRoute = MetodoPilar2IdentidadeRouteImport.update({
  id: '/identidade',
  path: '/identidade',
  getParentRoute: () => MetodoPilar2Route,
} as any)
const MetodoPilar2ConsultoriaImagemRoute =
  MetodoPilar2ConsultoriaImagemRouteImport.update({
    id: '/consultoria-imagem',
    path: '/consultoria-imagem',
    getParentRoute: () => MetodoPilar2Route,
  } as any)
const MetodoPilar2ConclusaoRoute = MetodoPilar2ConclusaoRouteImport.update({
  id: '/conclusao',
  path: '/conclusao',
  getParentRoute: () => MetodoPilar2Route,
} as any)
const MetodoPilar1DetetiveDoTempoRoute =
  MetodoPilar1DetetiveDoTempoRouteImport.update({
    id: '/detetive-do-tempo',
    path: '/detetive-do-tempo',
    getParentRoute: () => MetodoPilar1Route,
  } as any)
const MetodoPilar1ConclusaoRoute = MetodoPilar1ConclusaoRouteImport.update({
  id: '/conclusao',
  path: '/conclusao',
  getParentRoute: () => MetodoPilar1Route,
} as any)
const MetodoPilar1AprendaIaRoute = MetodoPilar1AprendaIaRouteImport.update({
  id: '/aprenda-ia',
  path: '/aprenda-ia',
  getParentRoute: () => MetodoPilar1Route,
} as any)
const MetodoConsultoriaIaComoUsarRoute =
  MetodoConsultoriaIaComoUsarRouteImport.update({
    id: '/como-usar',
    path: '/como-usar',
    getParentRoute: () => MetodoConsultoriaIaRoute,
  } as any)
const AuthenticatedAdminRankingRoute =
  AuthenticatedAdminRankingRouteImport.update({
    id: '/ranking',
    path: '/ranking',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMentoradasRoute =
  AuthenticatedAdminMentoradasRouteImport.update({
    id: '/mentoradas',
    path: '/mentoradas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConteudoRoute =
  AuthenticatedAdminConteudoRouteImport.update({
    id: '/conteudo',
    path: '/conteudo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const MetodoPilar3PaginaVendasIndexRoute =
  MetodoPilar3PaginaVendasIndexRouteImport.update({
    id: '/pagina-vendas/',
    path: '/pagina-vendas/',
    getParentRoute: () => MetodoPilar3Route,
  } as any)
const MetodoPilar3CriarProdutoIndexRoute =
  MetodoPilar3CriarProdutoIndexRouteImport.update({
    id: '/criar-produto/',
    path: '/criar-produto/',
    getParentRoute: () => MetodoPilar3Route,
  } as any)
const MetodoPilar3ComoEntregarIndexRoute =
  MetodoPilar3ComoEntregarIndexRouteImport.update({
    id: '/como-entregar/',
    path: '/como-entregar/',
    getParentRoute: () => MetodoPilar3Route,
  } as any)
const MetodoPilar2RedesSociaisIndexRoute =
  MetodoPilar2RedesSociaisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MetodoPilar2RedesSociaisRoute,
  } as any)
const MetodoPilar1DetetiveDoTempoIndexRoute =
  MetodoPilar1DetetiveDoTempoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MetodoPilar1DetetiveDoTempoRoute,
  } as any)
const MetodoPilar1AprendaIaIndexRoute =
  MetodoPilar1AprendaIaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MetodoPilar1AprendaIaRoute,
  } as any)
const MetodoPilar3PaginaVendasAulaRoute =
  MetodoPilar3PaginaVendasAulaRouteImport.update({
    id: '/pagina-vendas/$aula',
    path: '/pagina-vendas/$aula',
    getParentRoute: () => MetodoPilar3Route,
  } as any)
const MetodoPilar3FerramentasSlugRoute =
  MetodoPilar3FerramentasSlugRouteImport.update({
    id: '/ferramentas/$slug',
    path: '/ferramentas/$slug',
    getParentRoute: () => MetodoPilar3Route,
  } as any)
const MetodoPilar3CriarProdutoAulaRoute =
  MetodoPilar3CriarProdutoAulaRouteImport.update({
    id: '/criar-produto/$aula',
    path: '/criar-produto/$aula',
    getParentRoute: () => MetodoPilar3Route,
  } as any)
const MetodoPilar3ComoEntregarFormatoRoute =
  MetodoPilar3ComoEntregarFormatoRouteImport.update({
    id: '/como-entregar/$formato',
    path: '/como-entregar/$formato',
    getParentRoute: () => MetodoPilar3Route,
  } as any)
const MetodoPilar2RedesSociaisInstagramRoute =
  MetodoPilar2RedesSociaisInstagramRouteImport.update({
    id: '/instagram',
    path: '/instagram',
    getParentRoute: () => MetodoPilar2RedesSociaisRoute,
  } as any)
const MetodoPilar1DetetiveDoTempoRelatorioRoute =
  MetodoPilar1DetetiveDoTempoRelatorioRouteImport.update({
    id: '/relatorio',
    path: '/relatorio',
    getParentRoute: () => MetodoPilar1DetetiveDoTempoRoute,
  } as any)
const MetodoPilar1DetetiveDoTempoPlanoRoute =
  MetodoPilar1DetetiveDoTempoPlanoRouteImport.update({
    id: '/plano',
    path: '/plano',
    getParentRoute: () => MetodoPilar1DetetiveDoTempoRoute,
  } as any)
const MetodoPilar1AprendaIaVideosRoute =
  MetodoPilar1AprendaIaVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => MetodoPilar1AprendaIaRoute,
  } as any)
const MetodoPilar1AprendaIaProdutividadeRoute =
  MetodoPilar1AprendaIaProdutividadeRouteImport.update({
    id: '/produtividade',
    path: '/produtividade',
    getParentRoute: () => MetodoPilar1AprendaIaRoute,
  } as any)
const MetodoPilar1AprendaIaPrincipaisIasRoute =
  MetodoPilar1AprendaIaPrincipaisIasRouteImport.update({
    id: '/principais-ias',
    path: '/principais-ias',
    getParentRoute: () => MetodoPilar1AprendaIaRoute,
  } as any)
const MetodoPilar1AprendaIaToolRoute =
  MetodoPilar1AprendaIaToolRouteImport.update({
    id: '/$tool',
    path: '/$tool',
    getParentRoute: () => MetodoPilar1AprendaIaRoute,
  } as any)
const AuthenticatedAdminMentoradasIdRoute =
  AuthenticatedAdminMentoradasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminMentoradasRoute,
  } as any)
const MetodoPilar2RedesSociaisInstagramIndexRoute =
  MetodoPilar2RedesSociaisInstagramIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MetodoPilar2RedesSociaisInstagramRoute,
  } as any)
const MetodoPilar1AprendaIaToolIndexRoute =
  MetodoPilar1AprendaIaToolIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MetodoPilar1AprendaIaToolRoute,
  } as any)
const MetodoPilar2RedesSociaisInstagramFormatoRoute =
  MetodoPilar2RedesSociaisInstagramFormatoRouteImport.update({
    id: '/$formato',
    path: '/$formato',
    getParentRoute: () => MetodoPilar2RedesSociaisInstagramRoute,
  } as any)
const MetodoPilar1AprendaIaClaudeInstalarSkillsRoute =
  MetodoPilar1AprendaIaClaudeInstalarSkillsRouteImport.update({
    id: '/claude/instalar-skills',
    path: '/claude/instalar-skills',
    getParentRoute: () => MetodoPilar1AprendaIaRoute,
  } as any)
const MetodoPilar1AprendaIaToolLessonSlugRoute =
  MetodoPilar1AprendaIaToolLessonSlugRouteImport.update({
    id: '/$lessonSlug',
    path: '/$lessonSlug',
    getParentRoute: () => MetodoPilar1AprendaIaToolRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/conquistas': typeof ConquistasRoute
  '/doc-mestre': typeof DocMestreRoute
  '/glossario': typeof GlossarioRoute
  '/mensagens': typeof MensagensRoute
  '/metodo': typeof MetodoRouteWithChildren
  '/meus-projetos': typeof MeusProjetosRoute
  '/minha-base': typeof MinhaBaseRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/hotmart-webhook': typeof ApiHotmartWebhookRoute
  '/metodo/consultoria-ia': typeof MetodoConsultoriaIaRouteWithChildren
  '/metodo/pilar-1': typeof MetodoPilar1RouteWithChildren
  '/metodo/pilar-2': typeof MetodoPilar2RouteWithChildren
  '/metodo/pilar-3': typeof MetodoPilar3RouteWithChildren
  '/metodo/pilar-4': typeof MetodoPilar4RouteWithChildren
  '/metodo/': typeof MetodoIndexRoute
  '/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/admin/mentoradas': typeof AuthenticatedAdminMentoradasRouteWithChildren
  '/admin/ranking': typeof AuthenticatedAdminRankingRoute
  '/metodo/consultoria-ia/como-usar': typeof MetodoConsultoriaIaComoUsarRoute
  '/metodo/pilar-1/aprenda-ia': typeof MetodoPilar1AprendaIaRouteWithChildren
  '/metodo/pilar-1/conclusao': typeof MetodoPilar1ConclusaoRoute
  '/metodo/pilar-1/detetive-do-tempo': typeof MetodoPilar1DetetiveDoTempoRouteWithChildren
  '/metodo/pilar-2/conclusao': typeof MetodoPilar2ConclusaoRoute
  '/metodo/pilar-2/consultoria-imagem': typeof MetodoPilar2ConsultoriaImagemRoute
  '/metodo/pilar-2/identidade': typeof MetodoPilar2IdentidadeRoute
  '/metodo/pilar-2/identidade-visual': typeof MetodoPilar2IdentidadeVisualRoute
  '/metodo/pilar-2/metodo': typeof MetodoPilar2MetodoRoute
  '/metodo/pilar-2/pagina-profissional': typeof MetodoPilar2PaginaProfissionalRoute
  '/metodo/pilar-2/pesquisa-mercado': typeof MetodoPilar2PesquisaMercadoRoute
  '/metodo/pilar-2/redes-sociais': typeof MetodoPilar2RedesSociaisRouteWithChildren
  '/metodo/pilar-2/tom-de-voz': typeof MetodoPilar2TomDeVozRoute
  '/metodo/pilar-3/conclusao': typeof MetodoPilar3ConclusaoRoute
  '/metodo/pilar-3/descobrir': typeof MetodoPilar3DescobrirRoute
  '/metodo/pilar-3/validar-produto': typeof MetodoPilar3ValidarProdutoRoute
  '/metodo/pilar-4/alto-ticket': typeof MetodoPilar4AltoTicketRoute
  '/metodo/pilar-4/atalho-skill': typeof MetodoPilar4AtalhoSkillRoute
  '/metodo/pilar-4/conclusao': typeof MetodoPilar4ConclusaoRoute
  '/metodo/pilar-4/copy': typeof MetodoPilar4CopyRoute
  '/metodo/pilar-4/eventos-presenciais': typeof MetodoPilar4EventosPresenciaisRoute
  '/metodo/pilar-4/fundacao': typeof MetodoPilar4FundacaoRoute
  '/metodo/pilar-4/lancamentos': typeof MetodoPilar4LancamentosRoute
  '/metodo/pilar-4/low-ticket': typeof MetodoPilar4LowTicketRoute
  '/metodo/pilar-4/passo-a-passo': typeof MetodoPilar4PassoAPassoRoute
  '/metodo/pilar-4/trafego-pago': typeof MetodoPilar4TrafegoPagoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/metodo/consultoria-ia/': typeof MetodoConsultoriaIaIndexRoute
  '/metodo/pilar-1/': typeof MetodoPilar1IndexRoute
  '/metodo/pilar-2/': typeof MetodoPilar2IndexRoute
  '/metodo/pilar-3/': typeof MetodoPilar3IndexRoute
  '/metodo/pilar-4/': typeof MetodoPilar4IndexRoute
  '/admin/mentoradas/$id': typeof AuthenticatedAdminMentoradasIdRoute
  '/metodo/pilar-1/aprenda-ia/$tool': typeof MetodoPilar1AprendaIaToolRouteWithChildren
  '/metodo/pilar-1/aprenda-ia/principais-ias': typeof MetodoPilar1AprendaIaPrincipaisIasRoute
  '/metodo/pilar-1/aprenda-ia/produtividade': typeof MetodoPilar1AprendaIaProdutividadeRoute
  '/metodo/pilar-1/aprenda-ia/videos': typeof MetodoPilar1AprendaIaVideosRoute
  '/metodo/pilar-1/detetive-do-tempo/plano': typeof MetodoPilar1DetetiveDoTempoPlanoRoute
  '/metodo/pilar-1/detetive-do-tempo/relatorio': typeof MetodoPilar1DetetiveDoTempoRelatorioRoute
  '/metodo/pilar-2/redes-sociais/instagram': typeof MetodoPilar2RedesSociaisInstagramRouteWithChildren
  '/metodo/pilar-3/como-entregar/$formato': typeof MetodoPilar3ComoEntregarFormatoRoute
  '/metodo/pilar-3/criar-produto/$aula': typeof MetodoPilar3CriarProdutoAulaRoute
  '/metodo/pilar-3/ferramentas/$slug': typeof MetodoPilar3FerramentasSlugRoute
  '/metodo/pilar-3/pagina-vendas/$aula': typeof MetodoPilar3PaginaVendasAulaRoute
  '/metodo/pilar-1/aprenda-ia/': typeof MetodoPilar1AprendaIaIndexRoute
  '/metodo/pilar-1/detetive-do-tempo/': typeof MetodoPilar1DetetiveDoTempoIndexRoute
  '/metodo/pilar-2/redes-sociais/': typeof MetodoPilar2RedesSociaisIndexRoute
  '/metodo/pilar-3/como-entregar/': typeof MetodoPilar3ComoEntregarIndexRoute
  '/metodo/pilar-3/criar-produto/': typeof MetodoPilar3CriarProdutoIndexRoute
  '/metodo/pilar-3/pagina-vendas/': typeof MetodoPilar3PaginaVendasIndexRoute
  '/metodo/pilar-1/aprenda-ia/$tool/$lessonSlug': typeof MetodoPilar1AprendaIaToolLessonSlugRoute
  '/metodo/pilar-1/aprenda-ia/claude/instalar-skills': typeof MetodoPilar1AprendaIaClaudeInstalarSkillsRoute
  '/metodo/pilar-2/redes-sociais/instagram/$formato': typeof MetodoPilar2RedesSociaisInstagramFormatoRoute
  '/metodo/pilar-1/aprenda-ia/$tool/': typeof MetodoPilar1AprendaIaToolIndexRoute
  '/metodo/pilar-2/redes-sociais/instagram/': typeof MetodoPilar2RedesSociaisInstagramIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/conquistas': typeof ConquistasRoute
  '/doc-mestre': typeof DocMestreRoute
  '/glossario': typeof GlossarioRoute
  '/mensagens': typeof MensagensRoute
  '/meus-projetos': typeof MeusProjetosRoute
  '/minha-base': typeof MinhaBaseRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hotmart-webhook': typeof ApiHotmartWebhookRoute
  '/metodo': typeof MetodoIndexRoute
  '/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/admin/mentoradas': typeof AuthenticatedAdminMentoradasRouteWithChildren
  '/admin/ranking': typeof AuthenticatedAdminRankingRoute
  '/metodo/consultoria-ia/como-usar': typeof MetodoConsultoriaIaComoUsarRoute
  '/metodo/pilar-1/conclusao': typeof MetodoPilar1ConclusaoRoute
  '/metodo/pilar-2/conclusao': typeof MetodoPilar2ConclusaoRoute
  '/metodo/pilar-2/consultoria-imagem': typeof MetodoPilar2ConsultoriaImagemRoute
  '/metodo/pilar-2/identidade': typeof MetodoPilar2IdentidadeRoute
  '/metodo/pilar-2/identidade-visual': typeof MetodoPilar2IdentidadeVisualRoute
  '/metodo/pilar-2/metodo': typeof MetodoPilar2MetodoRoute
  '/metodo/pilar-2/pagina-profissional': typeof MetodoPilar2PaginaProfissionalRoute
  '/metodo/pilar-2/pesquisa-mercado': typeof MetodoPilar2PesquisaMercadoRoute
  '/metodo/pilar-2/tom-de-voz': typeof MetodoPilar2TomDeVozRoute
  '/metodo/pilar-3/conclusao': typeof MetodoPilar3ConclusaoRoute
  '/metodo/pilar-3/descobrir': typeof MetodoPilar3DescobrirRoute
  '/metodo/pilar-3/validar-produto': typeof MetodoPilar3ValidarProdutoRoute
  '/metodo/pilar-4/alto-ticket': typeof MetodoPilar4AltoTicketRoute
  '/metodo/pilar-4/atalho-skill': typeof MetodoPilar4AtalhoSkillRoute
  '/metodo/pilar-4/conclusao': typeof MetodoPilar4ConclusaoRoute
  '/metodo/pilar-4/copy': typeof MetodoPilar4CopyRoute
  '/metodo/pilar-4/eventos-presenciais': typeof MetodoPilar4EventosPresenciaisRoute
  '/metodo/pilar-4/fundacao': typeof MetodoPilar4FundacaoRoute
  '/metodo/pilar-4/lancamentos': typeof MetodoPilar4LancamentosRoute
  '/metodo/pilar-4/low-ticket': typeof MetodoPilar4LowTicketRoute
  '/metodo/pilar-4/passo-a-passo': typeof MetodoPilar4PassoAPassoRoute
  '/metodo/pilar-4/trafego-pago': typeof MetodoPilar4TrafegoPagoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/metodo/consultoria-ia': typeof MetodoConsultoriaIaIndexRoute
  '/metodo/pilar-1': typeof MetodoPilar1IndexRoute
  '/metodo/pilar-2': typeof MetodoPilar2IndexRoute
  '/metodo/pilar-3': typeof MetodoPilar3IndexRoute
  '/metodo/pilar-4': typeof MetodoPilar4IndexRoute
  '/admin/mentoradas/$id': typeof AuthenticatedAdminMentoradasIdRoute
  '/metodo/pilar-1/aprenda-ia/principais-ias': typeof MetodoPilar1AprendaIaPrincipaisIasRoute
  '/metodo/pilar-1/aprenda-ia/produtividade': typeof MetodoPilar1AprendaIaProdutividadeRoute
  '/metodo/pilar-1/aprenda-ia/videos': typeof MetodoPilar1AprendaIaVideosRoute
  '/metodo/pilar-1/detetive-do-tempo/plano': typeof MetodoPilar1DetetiveDoTempoPlanoRoute
  '/metodo/pilar-1/detetive-do-tempo/relatorio': typeof MetodoPilar1DetetiveDoTempoRelatorioRoute
  '/metodo/pilar-3/como-entregar/$formato': typeof MetodoPilar3ComoEntregarFormatoRoute
  '/metodo/pilar-3/criar-produto/$aula': typeof MetodoPilar3CriarProdutoAulaRoute
  '/metodo/pilar-3/ferramentas/$slug': typeof MetodoPilar3FerramentasSlugRoute
  '/metodo/pilar-3/pagina-vendas/$aula': typeof MetodoPilar3PaginaVendasAulaRoute
  '/metodo/pilar-1/aprenda-ia': typeof MetodoPilar1AprendaIaIndexRoute
  '/metodo/pilar-1/detetive-do-tempo': typeof MetodoPilar1DetetiveDoTempoIndexRoute
  '/metodo/pilar-2/redes-sociais': typeof MetodoPilar2RedesSociaisIndexRoute
  '/metodo/pilar-3/como-entregar': typeof MetodoPilar3ComoEntregarIndexRoute
  '/metodo/pilar-3/criar-produto': typeof MetodoPilar3CriarProdutoIndexRoute
  '/metodo/pilar-3/pagina-vendas': typeof MetodoPilar3PaginaVendasIndexRoute
  '/metodo/pilar-1/aprenda-ia/$tool/$lessonSlug': typeof MetodoPilar1AprendaIaToolLessonSlugRoute
  '/metodo/pilar-1/aprenda-ia/claude/instalar-skills': typeof MetodoPilar1AprendaIaClaudeInstalarSkillsRoute
  '/metodo/pilar-2/redes-sociais/instagram/$formato': typeof MetodoPilar2RedesSociaisInstagramFormatoRoute
  '/metodo/pilar-1/aprenda-ia/$tool': typeof MetodoPilar1AprendaIaToolIndexRoute
  '/metodo/pilar-2/redes-sociais/instagram': typeof MetodoPilar2RedesSociaisInstagramIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/conquistas': typeof ConquistasRoute
  '/doc-mestre': typeof DocMestreRoute
  '/glossario': typeof GlossarioRoute
  '/mensagens': typeof MensagensRoute
  '/metodo': typeof MetodoRouteWithChildren
  '/meus-projetos': typeof MeusProjetosRoute
  '/minha-base': typeof MinhaBaseRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/hotmart-webhook': typeof ApiHotmartWebhookRoute
  '/metodo/consultoria-ia': typeof MetodoConsultoriaIaRouteWithChildren
  '/metodo/pilar-1': typeof MetodoPilar1RouteWithChildren
  '/metodo/pilar-2': typeof MetodoPilar2RouteWithChildren
  '/metodo/pilar-3': typeof MetodoPilar3RouteWithChildren
  '/metodo/pilar-4': typeof MetodoPilar4RouteWithChildren
  '/metodo/': typeof MetodoIndexRoute
  '/_authenticated/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/_authenticated/admin/mentoradas': typeof AuthenticatedAdminMentoradasRouteWithChildren
  '/_authenticated/admin/ranking': typeof AuthenticatedAdminRankingRoute
  '/metodo/consultoria-ia/como-usar': typeof MetodoConsultoriaIaComoUsarRoute
  '/metodo/pilar-1/aprenda-ia': typeof MetodoPilar1AprendaIaRouteWithChildren
  '/metodo/pilar-1/conclusao': typeof MetodoPilar1ConclusaoRoute
  '/metodo/pilar-1/detetive-do-tempo': typeof MetodoPilar1DetetiveDoTempoRouteWithChildren
  '/metodo/pilar-2/conclusao': typeof MetodoPilar2ConclusaoRoute
  '/metodo/pilar-2/consultoria-imagem': typeof MetodoPilar2ConsultoriaImagemRoute
  '/metodo/pilar-2/identidade': typeof MetodoPilar2IdentidadeRoute
  '/metodo/pilar-2/identidade-visual': typeof MetodoPilar2IdentidadeVisualRoute
  '/metodo/pilar-2/metodo': typeof MetodoPilar2MetodoRoute
  '/metodo/pilar-2/pagina-profissional': typeof MetodoPilar2PaginaProfissionalRoute
  '/metodo/pilar-2/pesquisa-mercado': typeof MetodoPilar2PesquisaMercadoRoute
  '/metodo/pilar-2/redes-sociais': typeof MetodoPilar2RedesSociaisRouteWithChildren
  '/metodo/pilar-2/tom-de-voz': typeof MetodoPilar2TomDeVozRoute
  '/metodo/pilar-3/conclusao': typeof MetodoPilar3ConclusaoRoute
  '/metodo/pilar-3/descobrir': typeof MetodoPilar3DescobrirRoute
  '/metodo/pilar-3/validar-produto': typeof MetodoPilar3ValidarProdutoRoute
  '/metodo/pilar-4/alto-ticket': typeof MetodoPilar4AltoTicketRoute
  '/metodo/pilar-4/atalho-skill': typeof MetodoPilar4AtalhoSkillRoute
  '/metodo/pilar-4/conclusao': typeof MetodoPilar4ConclusaoRoute
  '/metodo/pilar-4/copy': typeof MetodoPilar4CopyRoute
  '/metodo/pilar-4/eventos-presenciais': typeof MetodoPilar4EventosPresenciaisRoute
  '/metodo/pilar-4/fundacao': typeof MetodoPilar4FundacaoRoute
  '/metodo/pilar-4/lancamentos': typeof MetodoPilar4LancamentosRoute
  '/metodo/pilar-4/low-ticket': typeof MetodoPilar4LowTicketRoute
  '/metodo/pilar-4/passo-a-passo': typeof MetodoPilar4PassoAPassoRoute
  '/metodo/pilar-4/trafego-pago': typeof MetodoPilar4TrafegoPagoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/metodo/consultoria-ia/': typeof MetodoConsultoriaIaIndexRoute
  '/metodo/pilar-1/': typeof MetodoPilar1IndexRoute
  '/metodo/pilar-2/': typeof MetodoPilar2IndexRoute
  '/metodo/pilar-3/': typeof MetodoPilar3IndexRoute
  '/metodo/pilar-4/': typeof MetodoPilar4IndexRoute
  '/_authenticated/admin/mentoradas/$id': typeof AuthenticatedAdminMentoradasIdRoute
  '/metodo/pilar-1/aprenda-ia/$tool': typeof MetodoPilar1AprendaIaToolRouteWithChildren
  '/metodo/pilar-1/aprenda-ia/principais-ias': typeof MetodoPilar1AprendaIaPrincipaisIasRoute
  '/metodo/pilar-1/aprenda-ia/produtividade': typeof MetodoPilar1AprendaIaProdutividadeRoute
  '/metodo/pilar-1/aprenda-ia/videos': typeof MetodoPilar1AprendaIaVideosRoute
  '/metodo/pilar-1/detetive-do-tempo/plano': typeof MetodoPilar1DetetiveDoTempoPlanoRoute
  '/metodo/pilar-1/detetive-do-tempo/relatorio': typeof MetodoPilar1DetetiveDoTempoRelatorioRoute
  '/metodo/pilar-2/redes-sociais/instagram': typeof MetodoPilar2RedesSociaisInstagramRouteWithChildren
  '/metodo/pilar-3/como-entregar/$formato': typeof MetodoPilar3ComoEntregarFormatoRoute
  '/metodo/pilar-3/criar-produto/$aula': typeof MetodoPilar3CriarProdutoAulaRoute
  '/metodo/pilar-3/ferramentas/$slug': typeof MetodoPilar3FerramentasSlugRoute
  '/metodo/pilar-3/pagina-vendas/$aula': typeof MetodoPilar3PaginaVendasAulaRoute
  '/metodo/pilar-1/aprenda-ia/': typeof MetodoPilar1AprendaIaIndexRoute
  '/metodo/pilar-1/detetive-do-tempo/': typeof MetodoPilar1DetetiveDoTempoIndexRoute
  '/metodo/pilar-2/redes-sociais/': typeof MetodoPilar2RedesSociaisIndexRoute
  '/metodo/pilar-3/como-entregar/': typeof MetodoPilar3ComoEntregarIndexRoute
  '/metodo/pilar-3/criar-produto/': typeof MetodoPilar3CriarProdutoIndexRoute
  '/metodo/pilar-3/pagina-vendas/': typeof MetodoPilar3PaginaVendasIndexRoute
  '/metodo/pilar-1/aprenda-ia/$tool/$lessonSlug': typeof MetodoPilar1AprendaIaToolLessonSlugRoute
  '/metodo/pilar-1/aprenda-ia/claude/instalar-skills': typeof MetodoPilar1AprendaIaClaudeInstalarSkillsRoute
  '/metodo/pilar-2/redes-sociais/instagram/$formato': typeof MetodoPilar2RedesSociaisInstagramFormatoRoute
  '/metodo/pilar-1/aprenda-ia/$tool/': typeof MetodoPilar1AprendaIaToolIndexRoute
  '/metodo/pilar-2/redes-sociais/instagram/': typeof MetodoPilar2RedesSociaisInstagramIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/assistente'
    | '/auth'
    | '/conquistas'
    | '/doc-mestre'
    | '/glossario'
    | '/mensagens'
    | '/metodo'
    | '/meus-projetos'
    | '/minha-base'
    | '/pending'
    | '/reset-password'
    | '/admin'
    | '/api/chat'
    | '/api/hotmart-webhook'
    | '/metodo/consultoria-ia'
    | '/metodo/pilar-1'
    | '/metodo/pilar-2'
    | '/metodo/pilar-3'
    | '/metodo/pilar-4'
    | '/metodo/'
    | '/admin/conteudo'
    | '/admin/mentoradas'
    | '/admin/ranking'
    | '/metodo/consultoria-ia/como-usar'
    | '/metodo/pilar-1/aprenda-ia'
    | '/metodo/pilar-1/conclusao'
    | '/metodo/pilar-1/detetive-do-tempo'
    | '/metodo/pilar-2/conclusao'
    | '/metodo/pilar-2/consultoria-imagem'
    | '/metodo/pilar-2/identidade'
    | '/metodo/pilar-2/identidade-visual'
    | '/metodo/pilar-2/metodo'
    | '/metodo/pilar-2/pagina-profissional'
    | '/metodo/pilar-2/pesquisa-mercado'
    | '/metodo/pilar-2/redes-sociais'
    | '/metodo/pilar-2/tom-de-voz'
    | '/metodo/pilar-3/conclusao'
    | '/metodo/pilar-3/descobrir'
    | '/metodo/pilar-3/validar-produto'
    | '/metodo/pilar-4/alto-ticket'
    | '/metodo/pilar-4/atalho-skill'
    | '/metodo/pilar-4/conclusao'
    | '/metodo/pilar-4/copy'
    | '/metodo/pilar-4/eventos-presenciais'
    | '/metodo/pilar-4/fundacao'
    | '/metodo/pilar-4/lancamentos'
    | '/metodo/pilar-4/low-ticket'
    | '/metodo/pilar-4/passo-a-passo'
    | '/metodo/pilar-4/trafego-pago'
    | '/admin/'
    | '/metodo/consultoria-ia/'
    | '/metodo/pilar-1/'
    | '/metodo/pilar-2/'
    | '/metodo/pilar-3/'
    | '/metodo/pilar-4/'
    | '/admin/mentoradas/$id'
    | '/metodo/pilar-1/aprenda-ia/$tool'
    | '/metodo/pilar-1/aprenda-ia/principais-ias'
    | '/metodo/pilar-1/aprenda-ia/produtividade'
    | '/metodo/pilar-1/aprenda-ia/videos'
    | '/metodo/pilar-1/detetive-do-tempo/plano'
    | '/metodo/pilar-1/detetive-do-tempo/relatorio'
    | '/metodo/pilar-2/redes-sociais/instagram'
    | '/metodo/pilar-3/como-entregar/$formato'
    | '/metodo/pilar-3/criar-produto/$aula'
    | '/metodo/pilar-3/ferramentas/$slug'
    | '/metodo/pilar-3/pagina-vendas/$aula'
    | '/metodo/pilar-1/aprenda-ia/'
    | '/metodo/pilar-1/detetive-do-tempo/'
    | '/metodo/pilar-2/redes-sociais/'
    | '/metodo/pilar-3/como-entregar/'
    | '/metodo/pilar-3/criar-produto/'
    | '/metodo/pilar-3/pagina-vendas/'
    | '/metodo/pilar-1/aprenda-ia/$tool/$lessonSlug'
    | '/metodo/pilar-1/aprenda-ia/claude/instalar-skills'
    | '/metodo/pilar-2/redes-sociais/instagram/$formato'
    | '/metodo/pilar-1/aprenda-ia/$tool/'
    | '/metodo/pilar-2/redes-sociais/instagram/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/assistente'
    | '/auth'
    | '/conquistas'
    | '/doc-mestre'
    | '/glossario'
    | '/mensagens'
    | '/meus-projetos'
    | '/minha-base'
    | '/pending'
    | '/reset-password'
    | '/api/chat'
    | '/api/hotmart-webhook'
    | '/metodo'
    | '/admin/conteudo'
    | '/admin/mentoradas'
    | '/admin/ranking'
    | '/metodo/consultoria-ia/como-usar'
    | '/metodo/pilar-1/conclusao'
    | '/metodo/pilar-2/conclusao'
    | '/metodo/pilar-2/consultoria-imagem'
    | '/metodo/pilar-2/identidade'
    | '/metodo/pilar-2/identidade-visual'
    | '/metodo/pilar-2/metodo'
    | '/metodo/pilar-2/pagina-profissional'
    | '/metodo/pilar-2/pesquisa-mercado'
    | '/metodo/pilar-2/tom-de-voz'
    | '/metodo/pilar-3/conclusao'
    | '/metodo/pilar-3/descobrir'
    | '/metodo/pilar-3/validar-produto'
    | '/metodo/pilar-4/alto-ticket'
    | '/metodo/pilar-4/atalho-skill'
    | '/metodo/pilar-4/conclusao'
    | '/metodo/pilar-4/copy'
    | '/metodo/pilar-4/eventos-presenciais'
    | '/metodo/pilar-4/fundacao'
    | '/metodo/pilar-4/lancamentos'
    | '/metodo/pilar-4/low-ticket'
    | '/metodo/pilar-4/passo-a-passo'
    | '/metodo/pilar-4/trafego-pago'
    | '/admin'
    | '/metodo/consultoria-ia'
    | '/metodo/pilar-1'
    | '/metodo/pilar-2'
    | '/metodo/pilar-3'
    | '/metodo/pilar-4'
    | '/admin/mentoradas/$id'
    | '/metodo/pilar-1/aprenda-ia/principais-ias'
    | '/metodo/pilar-1/aprenda-ia/produtividade'
    | '/metodo/pilar-1/aprenda-ia/videos'
    | '/metodo/pilar-1/detetive-do-tempo/plano'
    | '/metodo/pilar-1/detetive-do-tempo/relatorio'
    | '/metodo/pilar-3/como-entregar/$formato'
    | '/metodo/pilar-3/criar-produto/$aula'
    | '/metodo/pilar-3/ferramentas/$slug'
    | '/metodo/pilar-3/pagina-vendas/$aula'
    | '/metodo/pilar-1/aprenda-ia'
    | '/metodo/pilar-1/detetive-do-tempo'
    | '/metodo/pilar-2/redes-sociais'
    | '/metodo/pilar-3/como-entregar'
    | '/metodo/pilar-3/criar-produto'
    | '/metodo/pilar-3/pagina-vendas'
    | '/metodo/pilar-1/aprenda-ia/$tool/$lessonSlug'
    | '/metodo/pilar-1/aprenda-ia/claude/instalar-skills'
    | '/metodo/pilar-2/redes-sociais/instagram/$formato'
    | '/metodo/pilar-1/aprenda-ia/$tool'
    | '/metodo/pilar-2/redes-sociais/instagram'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agenda'
    | '/assistente'
    | '/auth'
    | '/conquistas'
    | '/doc-mestre'
    | '/glossario'
    | '/mensagens'
    | '/metodo'
    | '/meus-projetos'
    | '/minha-base'
    | '/pending'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/api/chat'
    | '/api/hotmart-webhook'
    | '/metodo/consultoria-ia'
    | '/metodo/pilar-1'
    | '/metodo/pilar-2'
    | '/metodo/pilar-3'
    | '/metodo/pilar-4'
    | '/metodo/'
    | '/_authenticated/admin/conteudo'
    | '/_authenticated/admin/mentoradas'
    | '/_authenticated/admin/ranking'
    | '/metodo/consultoria-ia/como-usar'
    | '/metodo/pilar-1/aprenda-ia'
    | '/metodo/pilar-1/conclusao'
    | '/metodo/pilar-1/detetive-do-tempo'
    | '/metodo/pilar-2/conclusao'
    | '/metodo/pilar-2/consultoria-imagem'
    | '/metodo/pilar-2/identidade'
    | '/metodo/pilar-2/identidade-visual'
    | '/metodo/pilar-2/metodo'
    | '/metodo/pilar-2/pagina-profissional'
    | '/metodo/pilar-2/pesquisa-mercado'
    | '/metodo/pilar-2/redes-sociais'
    | '/metodo/pilar-2/tom-de-voz'
    | '/metodo/pilar-3/conclusao'
    | '/metodo/pilar-3/descobrir'
    | '/metodo/pilar-3/validar-produto'
    | '/metodo/pilar-4/alto-ticket'
    | '/metodo/pilar-4/atalho-skill'
    | '/metodo/pilar-4/conclusao'
    | '/metodo/pilar-4/copy'
    | '/metodo/pilar-4/eventos-presenciais'
    | '/metodo/pilar-4/fundacao'
    | '/metodo/pilar-4/lancamentos'
    | '/metodo/pilar-4/low-ticket'
    | '/metodo/pilar-4/passo-a-passo'
    | '/metodo/pilar-4/trafego-pago'
    | '/_authenticated/admin/'
    | '/metodo/consultoria-ia/'
    | '/metodo/pilar-1/'
    | '/metodo/pilar-2/'
    | '/metodo/pilar-3/'
    | '/metodo/pilar-4/'
    | '/_authenticated/admin/mentoradas/$id'
    | '/metodo/pilar-1/aprenda-ia/$tool'
    | '/metodo/pilar-1/aprenda-ia/principais-ias'
    | '/metodo/pilar-1/aprenda-ia/produtividade'
    | '/metodo/pilar-1/aprenda-ia/videos'
    | '/metodo/pilar-1/detetive-do-tempo/plano'
    | '/metodo/pilar-1/detetive-do-tempo/relatorio'
    | '/metodo/pilar-2/redes-sociais/instagram'
    | '/metodo/pilar-3/como-entregar/$formato'
    | '/metodo/pilar-3/criar-produto/$aula'
    | '/metodo/pilar-3/ferramentas/$slug'
    | '/metodo/pilar-3/pagina-vendas/$aula'
    | '/metodo/pilar-1/aprenda-ia/'
    | '/metodo/pilar-1/detetive-do-tempo/'
    | '/metodo/pilar-2/redes-sociais/'
    | '/metodo/pilar-3/como-entregar/'
    | '/metodo/pilar-3/criar-produto/'
    | '/metodo/pilar-3/pagina-vendas/'
    | '/metodo/pilar-1/aprenda-ia/$tool/$lessonSlug'
    | '/metodo/pilar-1/aprenda-ia/claude/instalar-skills'
    | '/metodo/pilar-2/redes-sociais/instagram/$formato'
    | '/metodo/pilar-1/aprenda-ia/$tool/'
    | '/metodo/pilar-2/redes-sociais/instagram/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  AssistenteRoute: typeof AssistenteRoute
  AuthRoute: typeof AuthRoute
  ConquistasRoute: typeof ConquistasRoute
  DocMestreRoute: typeof DocMestreRoute
  GlossarioRoute: typeof GlossarioRoute
  MensagensRoute: typeof MensagensRoute
  MetodoRoute: typeof MetodoRouteWithChildren
  MeusProjetosRoute: typeof MeusProjetosRoute
  MinhaBaseRoute: typeof MinhaBaseRoute
  PendingRoute: typeof PendingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHotmartWebhookRoute: typeof ApiHotmartWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-base': {
      id: '/minha-base'
      path: '/minha-base'
      fullPath: '/minha-base'
      preLoaderRoute: typeof MinhaBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-projetos': {
      id: '/meus-projetos'
      path: '/meus-projetos'
      fullPath: '/meus-projetos'
      preLoaderRoute: typeof MeusProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc-mestre': {
      id: '/doc-mestre'
      path: '/doc-mestre'
      fullPath: '/doc-mestre'
      preLoaderRoute: typeof DocMestreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo/': {
      id: '/metodo/'
      path: '/'
      fullPath: '/metodo/'
      preLoaderRoute: typeof MetodoIndexRouteImport
      parentRoute: typeof MetodoRoute
    }
    '/metodo/pilar-4': {
      id: '/metodo/pilar-4'
      path: '/pilar-4'
      fullPath: '/metodo/pilar-4'
      preLoaderRoute: typeof MetodoPilar4RouteImport
      parentRoute: typeof MetodoRoute
    }
    '/metodo/pilar-3': {
      id: '/metodo/pilar-3'
      path: '/pilar-3'
      fullPath: '/metodo/pilar-3'
      preLoaderRoute: typeof MetodoPilar3RouteImport
      parentRoute: typeof MetodoRoute
    }
    '/metodo/pilar-2': {
      id: '/metodo/pilar-2'
      path: '/pilar-2'
      fullPath: '/metodo/pilar-2'
      preLoaderRoute: typeof MetodoPilar2RouteImport
      parentRoute: typeof MetodoRoute
    }
    '/metodo/pilar-1': {
      id: '/metodo/pilar-1'
      path: '/pilar-1'
      fullPath: '/metodo/pilar-1'
      preLoaderRoute: typeof MetodoPilar1RouteImport
      parentRoute: typeof MetodoRoute
    }
    '/metodo/consultoria-ia': {
      id: '/metodo/consultoria-ia'
      path: '/consultoria-ia'
      fullPath: '/metodo/consultoria-ia'
      preLoaderRoute: typeof MetodoConsultoriaIaRouteImport
      parentRoute: typeof MetodoRoute
    }
    '/api/hotmart-webhook': {
      id: '/api/hotmart-webhook'
      path: '/api/hotmart-webhook'
      fullPath: '/api/hotmart-webhook'
      preLoaderRoute: typeof ApiHotmartWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/metodo/pilar-4/': {
      id: '/metodo/pilar-4/'
      path: '/'
      fullPath: '/metodo/pilar-4/'
      preLoaderRoute: typeof MetodoPilar4IndexRouteImport
      parentRoute: typeof MetodoPilar4Route
    }
    '/metodo/pilar-3/': {
      id: '/metodo/pilar-3/'
      path: '/'
      fullPath: '/metodo/pilar-3/'
      preLoaderRoute: typeof MetodoPilar3IndexRouteImport
      parentRoute: typeof MetodoPilar3Route
    }
    '/metodo/pilar-2/': {
      id: '/metodo/pilar-2/'
      path: '/'
      fullPath: '/metodo/pilar-2/'
      preLoaderRoute: typeof MetodoPilar2IndexRouteImport
      parentRoute: typeof MetodoPilar2Route
    }
    '/metodo/pilar-1/': {
      id: '/metodo/pilar-1/'
      path: '/'
      fullPath: '/metodo/pilar-1/'
      preLoaderRoute: typeof MetodoPilar1IndexRouteImport
      parentRoute: typeof MetodoPilar1Route
    }
    '/metodo/consultoria-ia/': {
      id: '/metodo/consultoria-ia/'
      path: '/'
      fullPath: '/metodo/consultoria-ia/'
      preLoaderRoute: typeof MetodoConsultoriaIaIndexRouteImport
      parentRoute: typeof MetodoConsultoriaIaRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/metodo/pilar-4/trafego-pago': {
      id: '/metodo/pilar-4/trafego-pago'
      path: '/trafego-pago'
      fullPath: '/metodo/pilar-4/trafego-pago'
      preLoaderRoute: typeof MetodoPilar4TrafegoPagoRouteImport
      parentRoute: typeof MetodoPilar4Route
    }
    '/metodo/pilar-4/passo-a-passo': {
      id: '/metodo/pilar-4/passo-a-passo'
      path: '/passo-a-passo'
      fullPath: '/metodo/pilar-4/passo-a-passo'
      preLoaderRoute: typeof MetodoPilar4PassoAPassoRouteImport
      parentRoute: typeof MetodoPilar4Route
    }
    '/metodo/pilar-4/low-ticket': {
      id: '/metodo/pilar-4/low-ticket'
      path: '/low-ticket'
      fullPath: '/metodo/pilar-4/low-ticket'
      preLoaderRoute: typeof MetodoPilar4LowTicketRouteImport
      parentRoute: typeof MetodoPilar4Route
    }
    '/metodo/pilar-4/lancamentos': {
      id: '/metodo/pilar-4/lancamentos'
      path: '/lancamentos'
      fullPath: '/metodo/pilar-4/lancamentos'
      preLoaderRoute: typeof MetodoPilar4LancamentosRouteImport
      parentRoute: typeof MetodoPilar4Route
    }
    '/metodo/pilar-4/fundacao': {
      id: '/metodo/pilar-4/fundacao'
      path: '/fundacao'
      fullPath: '/metodo/pilar-4/fundacao'
      preLoaderRoute: typeof MetodoPilar4FundacaoRouteImport
      parentRoute: typeof MetodoPilar4Route
    }
    '/metodo/pilar-4/eventos-presenciais': {
      id: '/metodo/pilar-4/eventos-presenciais'
      path: '/eventos-presenciais'
      fullPath: '/metodo/pilar-4/eventos-presenciais'
      preLoaderRoute: typeof MetodoPilar4EventosPresenciaisRouteImport
      parentRoute: typeof MetodoPilar4Route
    }
    '/metodo/pilar-4/copy': {
      id: '/metodo/pilar-4/copy'
      path: '/copy'
      fullPath: '/metodo/pilar-4/copy'
      preLoaderRoute: typeof MetodoPilar4CopyRouteImport
      parentRoute: typeof MetodoPilar4Route
    }
    '/metodo/pilar-4/conclusao': {
      id: '/metodo/pilar-4/conclusao'
      path: '/conclusao'
      fullPath: '/metodo/pilar-4/conclusao'
      preLoaderRoute: typeof MetodoPilar4ConclusaoRouteImport
      parentRoute: typeof MetodoPilar4Route
    }
    '/metodo/pilar-4/atalho-skill': {
      id: '/metodo/pilar-4/atalho-skill'
      path: '/atalho-skill'
      fullPath: '/metodo/pilar-4/atalho-skill'
      preLoaderRoute: typeof MetodoPilar4AtalhoSkillRouteImport
      parentRoute: typeof MetodoPilar4Route
    }
    '/metodo/pilar-4/alto-ticket': {
      id: '/metodo/pilar-4/alto-ticket'
      path: '/alto-ticket'
      fullPath: '/metodo/pilar-4/alto-ticket'
      preLoaderRoute: typeof MetodoPilar4AltoTicketRouteImport
      parentRoute: typeof MetodoPilar4Route
    }
    '/metodo/pilar-3/validar-produto': {
      id: '/metodo/pilar-3/validar-produto'
      path: '/validar-produto'
      fullPath: '/metodo/pilar-3/validar-produto'
      preLoaderRoute: typeof MetodoPilar3ValidarProdutoRouteImport
      parentRoute: typeof MetodoPilar3Route
    }
    '/metodo/pilar-3/descobrir': {
      id: '/metodo/pilar-3/descobrir'
      path: '/descobrir'
      fullPath: '/metodo/pilar-3/descobrir'
      preLoaderRoute: typeof MetodoPilar3DescobrirRouteImport
      parentRoute: typeof MetodoPilar3Route
    }
    '/metodo/pilar-3/conclusao': {
      id: '/metodo/pilar-3/conclusao'
      path: '/conclusao'
      fullPath: '/metodo/pilar-3/conclusao'
      preLoaderRoute: typeof MetodoPilar3ConclusaoRouteImport
      parentRoute: typeof MetodoPilar3Route
    }
    '/metodo/pilar-2/tom-de-voz': {
      id: '/metodo/pilar-2/tom-de-voz'
      path: '/tom-de-voz'
      fullPath: '/metodo/pilar-2/tom-de-voz'
      preLoaderRoute: typeof MetodoPilar2TomDeVozRouteImport
      parentRoute: typeof MetodoPilar2Route
    }
    '/metodo/pilar-2/redes-sociais': {
      id: '/metodo/pilar-2/redes-sociais'
      path: '/redes-sociais'
      fullPath: '/metodo/pilar-2/redes-sociais'
      preLoaderRoute: typeof MetodoPilar2RedesSociaisRouteImport
      parentRoute: typeof MetodoPilar2Route
    }
    '/metodo/pilar-2/pesquisa-mercado': {
      id: '/metodo/pilar-2/pesquisa-mercado'
      path: '/pesquisa-mercado'
      fullPath: '/metodo/pilar-2/pesquisa-mercado'
      preLoaderRoute: typeof MetodoPilar2PesquisaMercadoRouteImport
      parentRoute: typeof MetodoPilar2Route
    }
    '/metodo/pilar-2/pagina-profissional': {
      id: '/metodo/pilar-2/pagina-profissional'
      path: '/pagina-profissional'
      fullPath: '/metodo/pilar-2/pagina-profissional'
      preLoaderRoute: typeof MetodoPilar2PaginaProfissionalRouteImport
      parentRoute: typeof MetodoPilar2Route
    }
    '/metodo/pilar-2/metodo': {
      id: '/metodo/pilar-2/metodo'
      path: '/metodo'
      fullPath: '/metodo/pilar-2/metodo'
      preLoaderRoute: typeof MetodoPilar2MetodoRouteImport
      parentRoute: typeof MetodoPilar2Route
    }
    '/metodo/pilar-2/identidade-visual': {
      id: '/metodo/pilar-2/identidade-visual'
      path: '/identidade-visual'
      fullPath: '/metodo/pilar-2/identidade-visual'
      preLoaderRoute: typeof MetodoPilar2IdentidadeVisualRouteImport
      parentRoute: typeof MetodoPilar2Route
    }
    '/metodo/pilar-2/identidade': {
      id: '/metodo/pilar-2/identidade'
      path: '/identidade'
      fullPath: '/metodo/pilar-2/identidade'
      preLoaderRoute: typeof MetodoPilar2IdentidadeRouteImport
      parentRoute: typeof MetodoPilar2Route
    }
    '/metodo/pilar-2/consultoria-imagem': {
      id: '/metodo/pilar-2/consultoria-imagem'
      path: '/consultoria-imagem'
      fullPath: '/metodo/pilar-2/consultoria-imagem'
      preLoaderRoute: typeof MetodoPilar2ConsultoriaImagemRouteImport
      parentRoute: typeof MetodoPilar2Route
    }
    '/metodo/pilar-2/conclusao': {
      id: '/metodo/pilar-2/conclusao'
      path: '/conclusao'
      fullPath: '/metodo/pilar-2/conclusao'
      preLoaderRoute: typeof MetodoPilar2ConclusaoRouteImport
      parentRoute: typeof MetodoPilar2Route
    }
    '/metodo/pilar-1/detetive-do-tempo': {
      id: '/metodo/pilar-1/detetive-do-tempo'
      path: '/detetive-do-tempo'
      fullPath: '/metodo/pilar-1/detetive-do-tempo'
      preLoaderRoute: typeof MetodoPilar1DetetiveDoTempoRouteImport
      parentRoute: typeof MetodoPilar1Route
    }
    '/metodo/pilar-1/conclusao': {
      id: '/metodo/pilar-1/conclusao'
      path: '/conclusao'
      fullPath: '/metodo/pilar-1/conclusao'
      preLoaderRoute: typeof MetodoPilar1ConclusaoRouteImport
      parentRoute: typeof MetodoPilar1Route
    }
    '/metodo/pilar-1/aprenda-ia': {
      id: '/metodo/pilar-1/aprenda-ia'
      path: '/aprenda-ia'
      fullPath: '/metodo/pilar-1/aprenda-ia'
      preLoaderRoute: typeof MetodoPilar1AprendaIaRouteImport
      parentRoute: typeof MetodoPilar1Route
    }
    '/metodo/consultoria-ia/como-usar': {
      id: '/metodo/consultoria-ia/como-usar'
      path: '/como-usar'
      fullPath: '/metodo/consultoria-ia/como-usar'
      preLoaderRoute: typeof MetodoConsultoriaIaComoUsarRouteImport
      parentRoute: typeof MetodoConsultoriaIaRoute
    }
    '/_authenticated/admin/ranking': {
      id: '/_authenticated/admin/ranking'
      path: '/ranking'
      fullPath: '/admin/ranking'
      preLoaderRoute: typeof AuthenticatedAdminRankingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/mentoradas': {
      id: '/_authenticated/admin/mentoradas'
      path: '/mentoradas'
      fullPath: '/admin/mentoradas'
      preLoaderRoute: typeof AuthenticatedAdminMentoradasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/conteudo': {
      id: '/_authenticated/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AuthenticatedAdminConteudoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/metodo/pilar-3/pagina-vendas/': {
      id: '/metodo/pilar-3/pagina-vendas/'
      path: '/pagina-vendas'
      fullPath: '/metodo/pilar-3/pagina-vendas/'
      preLoaderRoute: typeof MetodoPilar3PaginaVendasIndexRouteImport
      parentRoute: typeof MetodoPilar3Route
    }
    '/metodo/pilar-3/criar-produto/': {
      id: '/metodo/pilar-3/criar-produto/'
      path: '/criar-produto'
      fullPath: '/metodo/pilar-3/criar-produto/'
      preLoaderRoute: typeof MetodoPilar3CriarProdutoIndexRouteImport
      parentRoute: typeof MetodoPilar3Route
    }
    '/metodo/pilar-3/como-entregar/': {
      id: '/metodo/pilar-3/como-entregar/'
      path: '/como-entregar'
      fullPath: '/metodo/pilar-3/como-entregar/'
      preLoaderRoute: typeof MetodoPilar3ComoEntregarIndexRouteImport
      parentRoute: typeof MetodoPilar3Route
    }
    '/metodo/pilar-2/redes-sociais/': {
      id: '/metodo/pilar-2/redes-sociais/'
      path: '/'
      fullPath: '/metodo/pilar-2/redes-sociais/'
      preLoaderRoute: typeof MetodoPilar2RedesSociaisIndexRouteImport
      parentRoute: typeof MetodoPilar2RedesSociaisRoute
    }
    '/metodo/pilar-1/detetive-do-tempo/': {
      id: '/metodo/pilar-1/detetive-do-tempo/'
      path: '/'
      fullPath: '/metodo/pilar-1/detetive-do-tempo/'
      preLoaderRoute: typeof MetodoPilar1DetetiveDoTempoIndexRouteImport
      parentRoute: typeof MetodoPilar1DetetiveDoTempoRoute
    }
    '/metodo/pilar-1/aprenda-ia/': {
      id: '/metodo/pilar-1/aprenda-ia/'
      path: '/'
      fullPath: '/metodo/pilar-1/aprenda-ia/'
      preLoaderRoute: typeof MetodoPilar1AprendaIaIndexRouteImport
      parentRoute: typeof MetodoPilar1AprendaIaRoute
    }
    '/metodo/pilar-3/pagina-vendas/$aula': {
      id: '/metodo/pilar-3/pagina-vendas/$aula'
      path: '/pagina-vendas/$aula'
      fullPath: '/metodo/pilar-3/pagina-vendas/$aula'
      preLoaderRoute: typeof MetodoPilar3PaginaVendasAulaRouteImport
      parentRoute: typeof MetodoPilar3Route
    }
    '/metodo/pilar-3/ferramentas/$slug': {
      id: '/metodo/pilar-3/ferramentas/$slug'
      path: '/ferramentas/$slug'
      fullPath: '/metodo/pilar-3/ferramentas/$slug'
      preLoaderRoute: typeof MetodoPilar3FerramentasSlugRouteImport
      parentRoute: typeof MetodoPilar3Route
    }
    '/metodo/pilar-3/criar-produto/$aula': {
      id: '/metodo/pilar-3/criar-produto/$aula'
      path: '/criar-produto/$aula'
      fullPath: '/metodo/pilar-3/criar-produto/$aula'
      preLoaderRoute: typeof MetodoPilar3CriarProdutoAulaRouteImport
      parentRoute: typeof MetodoPilar3Route
    }
    '/metodo/pilar-3/como-entregar/$formato': {
      id: '/metodo/pilar-3/como-entregar/$formato'
      path: '/como-entregar/$formato'
      fullPath: '/metodo/pilar-3/como-entregar/$formato'
      preLoaderRoute: typeof MetodoPilar3ComoEntregarFormatoRouteImport
      parentRoute: typeof MetodoPilar3Route
    }
    '/metodo/pilar-2/redes-sociais/instagram': {
      id: '/metodo/pilar-2/redes-sociais/instagram'
      path: '/instagram'
      fullPath: '/metodo/pilar-2/redes-sociais/instagram'
      preLoaderRoute: typeof MetodoPilar2RedesSociaisInstagramRouteImport
      parentRoute: typeof MetodoPilar2RedesSociaisRoute
    }
    '/metodo/pilar-1/detetive-do-tempo/relatorio': {
      id: '/metodo/pilar-1/detetive-do-tempo/relatorio'
      path: '/relatorio'
      fullPath: '/metodo/pilar-1/detetive-do-tempo/relatorio'
      preLoaderRoute: typeof MetodoPilar1DetetiveDoTempoRelatorioRouteImport
      parentRoute: typeof MetodoPilar1DetetiveDoTempoRoute
    }
    '/metodo/pilar-1/detetive-do-tempo/plano': {
      id: '/metodo/pilar-1/detetive-do-tempo/plano'
      path: '/plano'
      fullPath: '/metodo/pilar-1/detetive-do-tempo/plano'
      preLoaderRoute: typeof MetodoPilar1DetetiveDoTempoPlanoRouteImport
      parentRoute: typeof MetodoPilar1DetetiveDoTempoRoute
    }
    '/metodo/pilar-1/aprenda-ia/videos': {
      id: '/metodo/pilar-1/aprenda-ia/videos'
      path: '/videos'
      fullPath: '/metodo/pilar-1/aprenda-ia/videos'
      preLoaderRoute: typeof MetodoPilar1AprendaIaVideosRouteImport
      parentRoute: typeof MetodoPilar1AprendaIaRoute
    }
    '/metodo/pilar-1/aprenda-ia/produtividade': {
      id: '/metodo/pilar-1/aprenda-ia/produtividade'
      path: '/produtividade'
      fullPath: '/metodo/pilar-1/aprenda-ia/produtividade'
      preLoaderRoute: typeof MetodoPilar1AprendaIaProdutividadeRouteImport
      parentRoute: typeof MetodoPilar1AprendaIaRoute
    }
    '/metodo/pilar-1/aprenda-ia/principais-ias': {
      id: '/metodo/pilar-1/aprenda-ia/principais-ias'
      path: '/principais-ias'
      fullPath: '/metodo/pilar-1/aprenda-ia/principais-ias'
      preLoaderRoute: typeof MetodoPilar1AprendaIaPrincipaisIasRouteImport
      parentRoute: typeof MetodoPilar1AprendaIaRoute
    }
    '/metodo/pilar-1/aprenda-ia/$tool': {
      id: '/metodo/pilar-1/aprenda-ia/$tool'
      path: '/$tool'
      fullPath: '/metodo/pilar-1/aprenda-ia/$tool'
      preLoaderRoute: typeof MetodoPilar1AprendaIaToolRouteImport
      parentRoute: typeof MetodoPilar1AprendaIaRoute
    }
    '/_authenticated/admin/mentoradas/$id': {
      id: '/_authenticated/admin/mentoradas/$id'
      path: '/$id'
      fullPath: '/admin/mentoradas/$id'
      preLoaderRoute: typeof AuthenticatedAdminMentoradasIdRouteImport
      parentRoute: typeof AuthenticatedAdminMentoradasRoute
    }
    '/metodo/pilar-2/redes-sociais/instagram/': {
      id: '/metodo/pilar-2/redes-sociais/instagram/'
      path: '/'
      fullPath: '/metodo/pilar-2/redes-sociais/instagram/'
      preLoaderRoute: typeof MetodoPilar2RedesSociaisInstagramIndexRouteImport
      parentRoute: typeof MetodoPilar2RedesSociaisInstagramRoute
    }
    '/metodo/pilar-1/aprenda-ia/$tool/': {
      id: '/metodo/pilar-1/aprenda-ia/$tool/'
      path: '/'
      fullPath: '/metodo/pilar-1/aprenda-ia/$tool/'
      preLoaderRoute: typeof MetodoPilar1AprendaIaToolIndexRouteImport
      parentRoute: typeof MetodoPilar1AprendaIaToolRoute
    }
    '/metodo/pilar-2/redes-sociais/instagram/$formato': {
      id: '/metodo/pilar-2/redes-sociais/instagram/$formato'
      path: '/$formato'
      fullPath: '/metodo/pilar-2/redes-sociais/instagram/$formato'
      preLoaderRoute: typeof MetodoPilar2RedesSociaisInstagramFormatoRouteImport
      parentRoute: typeof MetodoPilar2RedesSociaisInstagramRoute
    }
    '/metodo/pilar-1/aprenda-ia/claude/instalar-skills': {
      id: '/metodo/pilar-1/aprenda-ia/claude/instalar-skills'
      path: '/claude/instalar-skills'
      fullPath: '/metodo/pilar-1/aprenda-ia/claude/instalar-skills'
      preLoaderRoute: typeof MetodoPilar1AprendaIaClaudeInstalarSkillsRouteImport
      parentRoute: typeof MetodoPilar1AprendaIaRoute
    }
    '/metodo/pilar-1/aprenda-ia/$tool/$lessonSlug': {
      id: '/metodo/pilar-1/aprenda-ia/$tool/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/metodo/pilar-1/aprenda-ia/$tool/$lessonSlug'
      preLoaderRoute: typeof MetodoPilar1AprendaIaToolLessonSlugRouteImport
      parentRoute: typeof MetodoPilar1AprendaIaToolRoute
    }
  }
}

interface AuthenticatedAdminMentoradasRouteChildren {
  AuthenticatedAdminMentoradasIdRoute: typeof AuthenticatedAdminMentoradasIdRoute
}

const AuthenticatedAdminMentoradasRouteChildren: AuthenticatedAdminMentoradasRouteChildren =
  {
    AuthenticatedAdminMentoradasIdRoute: AuthenticatedAdminMentoradasIdRoute,
  }

const AuthenticatedAdminMentoradasRouteWithChildren =
  AuthenticatedAdminMentoradasRoute._addFileChildren(
    AuthenticatedAdminMentoradasRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminConteudoRoute: typeof AuthenticatedAdminConteudoRoute
  AuthenticatedAdminMentoradasRoute: typeof AuthenticatedAdminMentoradasRouteWithChildren
  AuthenticatedAdminRankingRoute: typeof AuthenticatedAdminRankingRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminConteudoRoute: AuthenticatedAdminConteudoRoute,
    AuthenticatedAdminMentoradasRoute:
      AuthenticatedAdminMentoradasRouteWithChildren,
    AuthenticatedAdminRankingRoute: AuthenticatedAdminRankingRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MetodoConsultoriaIaRouteChildren {
  MetodoConsultoriaIaComoUsarRoute: typeof MetodoConsultoriaIaComoUsarRoute
  MetodoConsultoriaIaIndexRoute: typeof MetodoConsultoriaIaIndexRoute
}

const MetodoConsultoriaIaRouteChildren: MetodoConsultoriaIaRouteChildren = {
  MetodoConsultoriaIaComoUsarRoute: MetodoConsultoriaIaComoUsarRoute,
  MetodoConsultoriaIaIndexRoute: MetodoConsultoriaIaIndexRoute,
}

const MetodoConsultoriaIaRouteWithChildren =
  MetodoConsultoriaIaRoute._addFileChildren(MetodoConsultoriaIaRouteChildren)

interface MetodoPilar1AprendaIaToolRouteChildren {
  MetodoPilar1AprendaIaToolLessonSlugRoute: typeof MetodoPilar1AprendaIaToolLessonSlugRoute
  MetodoPilar1AprendaIaToolIndexRoute: typeof MetodoPilar1AprendaIaToolIndexRoute
}

const MetodoPilar1AprendaIaToolRouteChildren: MetodoPilar1AprendaIaToolRouteChildren =
  {
    MetodoPilar1AprendaIaToolLessonSlugRoute:
      MetodoPilar1AprendaIaToolLessonSlugRoute,
    MetodoPilar1AprendaIaToolIndexRoute: MetodoPilar1AprendaIaToolIndexRoute,
  }

const MetodoPilar1AprendaIaToolRouteWithChildren =
  MetodoPilar1AprendaIaToolRoute._addFileChildren(
    MetodoPilar1AprendaIaToolRouteChildren,
  )

interface MetodoPilar1AprendaIaRouteChildren {
  MetodoPilar1AprendaIaToolRoute: typeof MetodoPilar1AprendaIaToolRouteWithChildren
  MetodoPilar1AprendaIaPrincipaisIasRoute: typeof MetodoPilar1AprendaIaPrincipaisIasRoute
  MetodoPilar1AprendaIaProdutividadeRoute: typeof MetodoPilar1AprendaIaProdutividadeRoute
  MetodoPilar1AprendaIaVideosRoute: typeof MetodoPilar1AprendaIaVideosRoute
  MetodoPilar1AprendaIaIndexRoute: typeof MetodoPilar1AprendaIaIndexRoute
  MetodoPilar1AprendaIaClaudeInstalarSkillsRoute: typeof MetodoPilar1AprendaIaClaudeInstalarSkillsRoute
}

const MetodoPilar1AprendaIaRouteChildren: MetodoPilar1AprendaIaRouteChildren = {
  MetodoPilar1AprendaIaToolRoute: MetodoPilar1AprendaIaToolRouteWithChildren,
  MetodoPilar1AprendaIaPrincipaisIasRoute:
    MetodoPilar1AprendaIaPrincipaisIasRoute,
  MetodoPilar1AprendaIaProdutividadeRoute:
    MetodoPilar1AprendaIaProdutividadeRoute,
  MetodoPilar1AprendaIaVideosRoute: MetodoPilar1AprendaIaVideosRoute,
  MetodoPilar1AprendaIaIndexRoute: MetodoPilar1AprendaIaIndexRoute,
  MetodoPilar1AprendaIaClaudeInstalarSkillsRoute:
    MetodoPilar1AprendaIaClaudeInstalarSkillsRoute,
}

const MetodoPilar1AprendaIaRouteWithChildren =
  MetodoPilar1AprendaIaRoute._addFileChildren(
    MetodoPilar1AprendaIaRouteChildren,
  )

interface MetodoPilar1DetetiveDoTempoRouteChildren {
  MetodoPilar1DetetiveDoTempoPlanoRoute: typeof MetodoPilar1DetetiveDoTempoPlanoRoute
  MetodoPilar1DetetiveDoTempoRelatorioRoute: typeof MetodoPilar1DetetiveDoTempoRelatorioRoute
  MetodoPilar1DetetiveDoTempoIndexRoute: typeof MetodoPilar1DetetiveDoTempoIndexRoute
}

const MetodoPilar1DetetiveDoTempoRouteChildren: MetodoPilar1DetetiveDoTempoRouteChildren =
  {
    MetodoPilar1DetetiveDoTempoPlanoRoute:
      MetodoPilar1DetetiveDoTempoPlanoRoute,
    MetodoPilar1DetetiveDoTempoRelatorioRoute:
      MetodoPilar1DetetiveDoTempoRelatorioRoute,
    MetodoPilar1DetetiveDoTempoIndexRoute:
      MetodoPilar1DetetiveDoTempoIndexRoute,
  }

const MetodoPilar1DetetiveDoTempoRouteWithChildren =
  MetodoPilar1DetetiveDoTempoRoute._addFileChildren(
    MetodoPilar1DetetiveDoTempoRouteChildren,
  )

interface MetodoPilar1RouteChildren {
  MetodoPilar1AprendaIaRoute: typeof MetodoPilar1AprendaIaRouteWithChildren
  MetodoPilar1ConclusaoRoute: typeof MetodoPilar1ConclusaoRoute
  MetodoPilar1DetetiveDoTempoRoute: typeof MetodoPilar1DetetiveDoTempoRouteWithChildren
  MetodoPilar1IndexRoute: typeof MetodoPilar1IndexRoute
}

const MetodoPilar1RouteChildren: MetodoPilar1RouteChildren = {
  MetodoPilar1AprendaIaRoute: MetodoPilar1AprendaIaRouteWithChildren,
  MetodoPilar1ConclusaoRoute: MetodoPilar1ConclusaoRoute,
  MetodoPilar1DetetiveDoTempoRoute:
    MetodoPilar1DetetiveDoTempoRouteWithChildren,
  MetodoPilar1IndexRoute: MetodoPilar1IndexRoute,
}

const MetodoPilar1RouteWithChildren = MetodoPilar1Route._addFileChildren(
  MetodoPilar1RouteChildren,
)

interface MetodoPilar2RedesSociaisInstagramRouteChildren {
  MetodoPilar2RedesSociaisInstagramFormatoRoute: typeof MetodoPilar2RedesSociaisInstagramFormatoRoute
  MetodoPilar2RedesSociaisInstagramIndexRoute: typeof MetodoPilar2RedesSociaisInstagramIndexRoute
}

const MetodoPilar2RedesSociaisInstagramRouteChildren: MetodoPilar2RedesSociaisInstagramRouteChildren =
  {
    MetodoPilar2RedesSociaisInstagramFormatoRoute:
      MetodoPilar2RedesSociaisInstagramFormatoRoute,
    MetodoPilar2RedesSociaisInstagramIndexRoute:
      MetodoPilar2RedesSociaisInstagramIndexRoute,
  }

const MetodoPilar2RedesSociaisInstagramRouteWithChildren =
  MetodoPilar2RedesSociaisInstagramRoute._addFileChildren(
    MetodoPilar2RedesSociaisInstagramRouteChildren,
  )

interface MetodoPilar2RedesSociaisRouteChildren {
  MetodoPilar2RedesSociaisInstagramRoute: typeof MetodoPilar2RedesSociaisInstagramRouteWithChildren
  MetodoPilar2RedesSociaisIndexRoute: typeof MetodoPilar2RedesSociaisIndexRoute
}

const MetodoPilar2RedesSociaisRouteChildren: MetodoPilar2RedesSociaisRouteChildren =
  {
    MetodoPilar2RedesSociaisInstagramRoute:
      MetodoPilar2RedesSociaisInstagramRouteWithChildren,
    MetodoPilar2RedesSociaisIndexRoute: MetodoPilar2RedesSociaisIndexRoute,
  }

const MetodoPilar2RedesSociaisRouteWithChildren =
  MetodoPilar2RedesSociaisRoute._addFileChildren(
    MetodoPilar2RedesSociaisRouteChildren,
  )

interface MetodoPilar2RouteChildren {
  MetodoPilar2ConclusaoRoute: typeof MetodoPilar2ConclusaoRoute
  MetodoPilar2ConsultoriaImagemRoute: typeof MetodoPilar2ConsultoriaImagemRoute
  MetodoPilar2IdentidadeRoute: typeof MetodoPilar2IdentidadeRoute
  MetodoPilar2IdentidadeVisualRoute: typeof MetodoPilar2IdentidadeVisualRoute
  MetodoPilar2MetodoRoute: typeof MetodoPilar2MetodoRoute
  MetodoPilar2PaginaProfissionalRoute: typeof MetodoPilar2PaginaProfissionalRoute
  MetodoPilar2PesquisaMercadoRoute: typeof MetodoPilar2PesquisaMercadoRoute
  MetodoPilar2RedesSociaisRoute: typeof MetodoPilar2RedesSociaisRouteWithChildren
  MetodoPilar2TomDeVozRoute: typeof MetodoPilar2TomDeVozRoute
  MetodoPilar2IndexRoute: typeof MetodoPilar2IndexRoute
}

const MetodoPilar2RouteChildren: MetodoPilar2RouteChildren = {
  MetodoPilar2ConclusaoRoute: MetodoPilar2ConclusaoRoute,
  MetodoPilar2ConsultoriaImagemRoute: MetodoPilar2ConsultoriaImagemRoute,
  MetodoPilar2IdentidadeRoute: MetodoPilar2IdentidadeRoute,
  MetodoPilar2IdentidadeVisualRoute: MetodoPilar2IdentidadeVisualRoute,
  MetodoPilar2MetodoRoute: MetodoPilar2MetodoRoute,
  MetodoPilar2PaginaProfissionalRoute: MetodoPilar2PaginaProfissionalRoute,
  MetodoPilar2PesquisaMercadoRoute: MetodoPilar2PesquisaMercadoRoute,
  MetodoPilar2RedesSociaisRoute: MetodoPilar2RedesSociaisRouteWithChildren,
  MetodoPilar2TomDeVozRoute: MetodoPilar2TomDeVozRoute,
  MetodoPilar2IndexRoute: MetodoPilar2IndexRoute,
}

const MetodoPilar2RouteWithChildren = MetodoPilar2Route._addFileChildren(
  MetodoPilar2RouteChildren,
)

interface MetodoPilar3RouteChildren {
  MetodoPilar3ConclusaoRoute: typeof MetodoPilar3ConclusaoRoute
  MetodoPilar3DescobrirRoute: typeof MetodoPilar3DescobrirRoute
  MetodoPilar3ValidarProdutoRoute: typeof MetodoPilar3ValidarProdutoRoute
  MetodoPilar3IndexRoute: typeof MetodoPilar3IndexRoute
  MetodoPilar3ComoEntregarFormatoRoute: typeof MetodoPilar3ComoEntregarFormatoRoute
  MetodoPilar3CriarProdutoAulaRoute: typeof MetodoPilar3CriarProdutoAulaRoute
  MetodoPilar3FerramentasSlugRoute: typeof MetodoPilar3FerramentasSlugRoute
  MetodoPilar3PaginaVendasAulaRoute: typeof MetodoPilar3PaginaVendasAulaRoute
  MetodoPilar3ComoEntregarIndexRoute: typeof MetodoPilar3ComoEntregarIndexRoute
  MetodoPilar3CriarProdutoIndexRoute: typeof MetodoPilar3CriarProdutoIndexRoute
  MetodoPilar3PaginaVendasIndexRoute: typeof MetodoPilar3PaginaVendasIndexRoute
}

const MetodoPilar3RouteChildren: MetodoPilar3RouteChildren = {
  MetodoPilar3ConclusaoRoute: MetodoPilar3ConclusaoRoute,
  MetodoPilar3DescobrirRoute: MetodoPilar3DescobrirRoute,
  MetodoPilar3ValidarProdutoRoute: MetodoPilar3ValidarProdutoRoute,
  MetodoPilar3IndexRoute: MetodoPilar3IndexRoute,
  MetodoPilar3ComoEntregarFormatoRoute: MetodoPilar3ComoEntregarFormatoRoute,
  MetodoPilar3CriarProdutoAulaRoute: MetodoPilar3CriarProdutoAulaRoute,
  MetodoPilar3FerramentasSlugRoute: MetodoPilar3FerramentasSlugRoute,
  MetodoPilar3PaginaVendasAulaRoute: MetodoPilar3PaginaVendasAulaRoute,
  MetodoPilar3ComoEntregarIndexRoute: MetodoPilar3ComoEntregarIndexRoute,
  MetodoPilar3CriarProdutoIndexRoute: MetodoPilar3CriarProdutoIndexRoute,
  MetodoPilar3PaginaVendasIndexRoute: MetodoPilar3PaginaVendasIndexRoute,
}

const MetodoPilar3RouteWithChildren = MetodoPilar3Route._addFileChildren(
  MetodoPilar3RouteChildren,
)

interface MetodoPilar4RouteChildren {
  MetodoPilar4AltoTicketRoute: typeof MetodoPilar4AltoTicketRoute
  MetodoPilar4AtalhoSkillRoute: typeof MetodoPilar4AtalhoSkillRoute
  MetodoPilar4ConclusaoRoute: typeof MetodoPilar4ConclusaoRoute
  MetodoPilar4CopyRoute: typeof MetodoPilar4CopyRoute
  MetodoPilar4EventosPresenciaisRoute: typeof MetodoPilar4EventosPresenciaisRoute
  MetodoPilar4FundacaoRoute: typeof MetodoPilar4FundacaoRoute
  MetodoPilar4LancamentosRoute: typeof MetodoPilar4LancamentosRoute
  MetodoPilar4LowTicketRoute: typeof MetodoPilar4LowTicketRoute
  MetodoPilar4PassoAPassoRoute: typeof MetodoPilar4PassoAPassoRoute
  MetodoPilar4TrafegoPagoRoute: typeof MetodoPilar4TrafegoPagoRoute
  MetodoPilar4IndexRoute: typeof MetodoPilar4IndexRoute
}

const MetodoPilar4RouteChildren: MetodoPilar4RouteChildren = {
  MetodoPilar4AltoTicketRoute: MetodoPilar4AltoTicketRoute,
  MetodoPilar4AtalhoSkillRoute: MetodoPilar4AtalhoSkillRoute,
  MetodoPilar4ConclusaoRoute: MetodoPilar4ConclusaoRoute,
  MetodoPilar4CopyRoute: MetodoPilar4CopyRoute,
  MetodoPilar4EventosPresenciaisRoute: MetodoPilar4EventosPresenciaisRoute,
  MetodoPilar4FundacaoRoute: MetodoPilar4FundacaoRoute,
  MetodoPilar4LancamentosRoute: MetodoPilar4LancamentosRoute,
  MetodoPilar4LowTicketRoute: MetodoPilar4LowTicketRoute,
  MetodoPilar4PassoAPassoRoute: MetodoPilar4PassoAPassoRoute,
  MetodoPilar4TrafegoPagoRoute: MetodoPilar4TrafegoPagoRoute,
  MetodoPilar4IndexRoute: MetodoPilar4IndexRoute,
}

const MetodoPilar4RouteWithChildren = MetodoPilar4Route._addFileChildren(
  MetodoPilar4RouteChildren,
)

interface MetodoRouteChildren {
  MetodoConsultoriaIaRoute: typeof MetodoConsultoriaIaRouteWithChildren
  MetodoPilar1Route: typeof MetodoPilar1RouteWithChildren
  MetodoPilar2Route: typeof MetodoPilar2RouteWithChildren
  MetodoPilar3Route: typeof MetodoPilar3RouteWithChildren
  MetodoPilar4Route: typeof MetodoPilar4RouteWithChildren
  MetodoIndexRoute: typeof MetodoIndexRoute
}

const MetodoRouteChildren: MetodoRouteChildren = {
  MetodoConsultoriaIaRoute: MetodoConsultoriaIaRouteWithChildren,
  MetodoPilar1Route: MetodoPilar1RouteWithChildren,
  MetodoPilar2Route: MetodoPilar2RouteWithChildren,
  MetodoPilar3Route: MetodoPilar3RouteWithChildren,
  MetodoPilar4Route: MetodoPilar4RouteWithChildren,
  MetodoIndexRoute: MetodoIndexRoute,
}

const MetodoRouteWithChildren =
  MetodoRoute._addFileChildren(MetodoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgendaRoute: AgendaRoute,
  AssistenteRoute: AssistenteRoute,
  AuthRoute: AuthRoute,
  ConquistasRoute: ConquistasRoute,
  DocMestreRoute: DocMestreRoute,
  GlossarioRoute: GlossarioRoute,
  MensagensRoute: MensagensRoute,
  MetodoRoute: MetodoRouteWithChildren,
  MeusProjetosRoute: MeusProjetosRoute,
  MinhaBaseRoute: MinhaBaseRoute,
  PendingRoute: PendingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHotmartWebhookRoute: ApiHotmartWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
